# Cluster-wide role to list namespaces only
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-lister
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-test-sa-namespace-lister
subjects:
- kind: ServiceAccount
  name: rbac-test-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: namespace-lister
  apiGroup: rbac.authorization.k8s.io
---
# Read-only access to rbac-a namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rbac-a
  name: rbac-a-reader
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-test-sa-rbac-a-reader
  namespace: rbac-a
subjects:
- kind: ServiceAccount
  name: rbac-test-sa
  namespace: default
roleRef:
  kind: Role
  name: rbac-a-reader
  apiGroup: rbac.authorization.k8s.io
---
# Full access to rbac-b namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rbac-b
  name: rbac-b-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-test-sa-rbac-b-admin
  namespace: rbac-b
subjects:
- kind: ServiceAccount
  name: rbac-test-sa
  namespace: default
roleRef:
  kind: Role
  name: rbac-b-admin
  apiGroup: rbac.authorization.k8s.io
